### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by altair984** [rebecamurillo/astro-blog-i18n-starter#1]
Hola, tu plantilla de post multi idioma es perfecta, me ha encantado, muchas gracias. He intentado hacer un blog para comprender astro teniendo tu plantilla como base para tener dos idiomas, peor me encuentro con el problema de la paginación en el index del blog. Siempre muestra los dos primeros post al cambiar de pagina, lo mismo no estoy haciendo el uso correcto para paginar.

Seria mucho pedirte sobre el añadido del componente paginación a tu proyecto?

De todas formas, muchísimas gracias por todo, un saludo :)

**Comment by rebecamurillo** [comment]
Hola @altair984 
Es una muy buena sugerencia. 
Lo tomo en cuenta para un fix en el proximo mes. 
Un saludo, 
Rebeca

**Comment by altair984** [comment]
Hola, gracias por contestar, esperare con mucho entusiasmo por esa implementación. 
Me agrada que mi sugerencia te haya gustado, un saludo :)
